const menuData = [
    {
        id: 1,
        name: "Kerala Matta Rice",
        nameML: "കുത്തരി ചോറ്",
        price: 80,
        category: "rice",
        description: "Nutritious red rice, the heart of the Sadya.",
        descriptionML: "സദ്യയുടെ പ്രധാന ഭാഗമായ പോഷകസമൃദ്ധമായ കുത്തരി.",
        image: "images/mattarice.webp",
        tags: ["Staple", "Nutritious"],
        tagsML: ["പ്രധാനം", "പോഷകപ്രദം"]
    },
    {
        id: 2,
        name: "Sambar",
        nameML: "സാമ്പാർ",
        price: 60,
        category: "curry",
        description: "Aromatic lentil stew rich with garden vegetables.",
        descriptionML: "പച്ചക്കറികളും പരിപ്പും ചേര്ന്ന സുഗന്ധപൂരിതമായ കറി.",
        image: "images/sambar.webp",
        tags: ["Spiced", "Flavorful"],
        tagsML: ["സുഗന്ധം", "രുചികരം"]
    },
    {
        id: 3,
        name: "Avial",
        nameML: "അവിയൽ",
        price: 90,
        category: "curry",
        description: "A divine blend of vegetables, coconut, and curd.",
        descriptionML: "പച്ചക്കറികളും തേങ്ങയും തൈരും ചേർന്ന ദിവ്യമായ കൂട്ട്.",
        image: "images/avial.webp",
        tags: ["Traditional", "Mild"],
        tagsML: ["പരമ്പരാഗതം", "മിതമായത്"]
    },
    {
        id: 4,
        name: "Parippu Curry",
        nameML: "പരിപ്പ് കറി",
        price: 50,
        category: "curry",
        description: "Golden moong dal seasoned with pure ghee.",
        descriptionML: "നെയ്യ് ചേർത്ത സ്വാദിഷ്ടമായ ചെറുപയർ പരിപ്പ് കറി.",
        image: "images/parippucurry.webp",
        tags: ["Comfort", "Classic"],
        tagsML: ["ലളിതം", "ക്ലാസിക്"]
    },
    {
        id: 5,
        name: "Cabbage Thoran",
        nameML: "ക്യാബേജ് തോരൻ",
        price: 70,
        category: "side",
        description: "Stir-fried farm fresh cabbage with grated coconut.",
        descriptionML: "തേങ്ങ ചേർത്ത ഫ്രഷ് ക്യാബേജ് തോരൻ.",
        image: "images/thoran.webp",
        tags: ["Fresh", "Side"],
        tagsML: ["ഫ്രഷ്", "തോരൻ"]
    },
    {
        id: 6,
        name: "Kaalan",
        nameML: "കാളൻ",
        price: 85,
        category: "curry",
        description: "Thick yogurt-based curry with sun-dried yam.",
        descriptionML: "തൈരും ചേനയും ചേർത്ത കുറുകിയ കറി.",
        image: "images/kaalan.webp",
        tags: ["Tangy", "Preserved"],
        tagsML: ["പുളിപ്പുള്ളത്", "പരമ്പരാഗതം"]
    },
    {
        id: 7,
        name: "Pappadam",
        nameML: "പപ്പടം",
        price: 20,
        category: "side",
        description: "Crispy lentil wafers, a festive crunch.",
        descriptionML: "സദ്യക്ക് ഒഴിവാക്കാനാവാത്ത മൊരിഞ്ഞ പപ്പടം.",
        image: "images/pappadam.webp",
        tags: ["Crispy", "Essential"],
        tagsML: ["മൊരിഞ്ഞത്", "നിർബന്ധം"]
    },
    {
        id: 8,
        name: "Ada Pradhaman",
        nameML: "അട പ്രഥമൻ",
        price: 120,
        category: "dessert",
        description: "Royal sweet delicacy with rice flakes and jaggery.",
        descriptionML: "അടയും ശർക്കരയും ചേർത്ത രാജകീയ പായസം.",
        image: "images/pradhaman.webp",
        tags: ["Sweet", "Signature"],
        tagsML: ["മധുരം", "സ്പെഷ്യൽ"]
    },
    {
        id: 9,
        name: "Palada Payasam",
        nameML: "പാലട പായസം",
        price: 130,
        category: "dessert",
        description: "Divine rice pudding slow-cooked in milk.",
        descriptionML: "പാലിൽ കുറുക്കിയെടുത്ത രുചികരമായ പായസം.",
        image: "images/paayasam.webp",
        tags: ["Creamy", "Divine"],
        tagsML: ["പാൽരുചി", "ദിവ്യം"]
    }
];