/* ============================================
   DATA — Translations & Menu Items
   ============================================ */

const translations = {
    en: {
        title: "Tharavadu",
        nav_home: "Poomukham",
        nav_menu: "Oottupura",
        nav_about: "Heritage",
        nav_contact: "Contact",
        hero_title: "Welcome Home",
        hero_subtitle: "Experience the divine taste of tradition in our ancestral courtyard.",
        hero_cta: "Enter the Oottupura",
        menu_title: "The Grand Sadya",
        menu_subtitle: "Served fresh from our ancestral kitchen",
        search_placeholder: "Search for delicacies...",
        filter_all: "All",
        filter_rice: "Rice",
        filter_curry: "Curries",
        filter_side: "Sides",
        filter_dessert: "Desserts",
        cart_title: "Your Offering",
        cart_empty: "Your leaf is empty. Please serve.",
        cart_total: "Dakshina (Total):",
        cart_checkout: "Serve Now",
        modal_title: "Blessed!",
        modal_msg: "Your Sadya has been served with love and tradition.",
        modal_btn: "Namaskaram",
        footer: "&copy; 2026 The Serene Tharavadu. Preserving Tradition.",
        add_btn: "Offer to Leaf",
        toggle_btn: "മലയാളം",
        view_leaf_btn: "View Leaf",
        no_results: "No blessings found with that name.",
        heritage_title: "Our Heritage",
        heritage_content: "The Serene Tharavadu stands as a testament to Kerala's rich architectural legacy. Built over a century ago, this ancestral home has witnessed generations of tradition, hospitality, and culinary excellence. Our kitchen still follows the age-old methods of slow-cooking over wood fires, preserving the authentic flavors passed down through time.",
        heritage_content_2: "Every corner of our Tharavadu tells a story. From the hand-carved wooden pillars to the open courtyards that breathe with the monsoon rain, we have preserved the sanctity of this space to offer you more than just a meal—an experience of homecoming.",
        contact_title: "Get in Touch",
        contact_name: "Name",
        contact_email: "Email",
        contact_message: "Message",
        contact_send: "Send Message",
        contact_info: "Visit Us",
        contact_address: "Address",
        addr_line: "Amal Jyothi College of Engineering, Kanjirapally, Kerala",
        phone_label: "Phone",
        email_label: "Email"
    },
    ml: {
        title: "തറവാട്",
        nav_home: "പൂമുഖം",
        nav_menu: "ഊട്ടുപുര",
        nav_about: "പൈതൃകം",
        nav_contact: "ബന്ധപ്പെടുക",
        hero_title: "സ്വാഗതം",
        hero_subtitle: "ഞങ്ങളുടെ തറവാട്ടിലെ പരമ്പരാഗത രുചി അനുഭവിക്കൂ.",
        hero_cta: "ഊട്ടുപുരയിലേക്ക്",
        menu_title: "സദ്യ വട്ടം",
        menu_subtitle: "ഞങ്ങളുടെ തറവാട്ടിലെ അടുക്കളയിൽ നിന്ന്",
        search_placeholder: "വിഭവങ്ങൾ തിരയുക...",
        filter_all: "എല്ലാം",
        filter_rice: "ചോറ്",
        filter_curry: "കറികൾ",
        filter_side: "വിഭവങ്ങൾ",
        filter_dessert: "പായസം",
        cart_title: "നിങ്ങളുടെ ഇല",
        cart_empty: "ഇല കാലിയാണ്. വിളമ്പാം.",
        cart_total: "ദക്ഷിണ (ആകെ):",
        cart_checkout: "വിളമ്പുക",
        modal_title: "അനുഗ്രഹീതം!",
        modal_msg: "സ്നേഹത്തോടും പാരമ്പര്യത്തോടും കൂടി സദ്യ വിളമ്പി.",
        modal_btn: "നമസ്കാരം",
        footer: "&copy; 2026 നിർമ്മലമായ തറവാട്. പാരമ്പര്യം കാത്തുസൂക്ഷിക്കുന്നു.",
        add_btn: "ഇലയിൽ വിളമ്പുക",
        toggle_btn: "English",
        view_leaf_btn: "ഇല കാണുക",
        no_results: "ഈ പേരിലൊരു വിഭവം കണ്ടെത്തിയില്ല.",
        heritage_title: "ഞങ്ങളുടെ പൈതൃകം",
        heritage_content: "കേരളത്തിന്റെ സമ്പന്നമായ വാസ്തുവിദ്യാ പൈതൃകത്തിന്റെ സാക്ഷ്യപത്രമാണ് ഈ തറവാട്. ഒരു നൂറ്റാണ്ടിലധികം പഴക്കമുള്ള ഈ പൈതൃക ഭവനം തലമുറകളുടെ പാരമ്പര്യം, അതിഥി സൽക്കാരം, പാചക മികവ് എന്നിവയ്ക്ക് സാക്ഷ്യം വഹിച്ചിട്ടുണ്ട്. ഞങ്ങളുടെ അടുക്കള ഇന്നും വിറകടുപ്പിലെ പഴയ പാചകരീതികൾ പിന്തുടരുന്നു, കാലങ്ങളായി കൈമാറിവന്ന യഥാർത്ഥ രുചികൾ സംരക്ഷിക്കുന്നു.",
        heritage_content_2: "ഞങ്ങളുടെ തറവാടിന്റെ ഓരോ മൂലയും ഒരു കഥ പറയുന്നു. കൈകൊണ്ട് കൊത്തിയെടുത്ത മരത്തൂണുകൾ മുതൽ മഴക്കാലത്ത് ശ്വസിക്കുന്ന തുറന്ന മുറ്റങ്ങൾ വരെ, ഈ ഇടത്തിന്റെ പവിത്രത ഞങ്ങൾ സംരക്ഷിച്ചിരിക്കുന്നു — നിങ്ങൾക്ക് ഒരു ഭക്ഷണത്തേക്കാൾ കൂടുതൽ, ഒരു വീട്ടിലേക്കുള്ള മടക്കയാത്രയുടെ അനുഭവം നൽകാൻ.",
        contact_title: "ബന്ധപ്പെടുക",
        contact_name: "പേര്",
        contact_email: "ഇമെയിൽ",
        contact_message: "സന്ദേശം",
        contact_send: "അയക്കുക",
        contact_info: "സന്ദർശിക്കൂ",
        contact_address: "വിലാസം",
        addr_line: "അമൽ ജ്യോതി കോളേജ് ഓഫ് എഞ്ചിനീയറിംഗ്, കാഞ്ഞിരപ്പള്ളി, കേരളം",
        phone_label: "ഫോൺ",
        email_label: "ഇമെയിൽ"
    }
};

const menuData = [
    {
        id: 1,
        name: "Kerala Matta Rice",
        nameML: "കുത്തരി ചോറ്",
        price: 80,
        category: "rice",
        description: "Nutritious red rice, the heart of the Sadya.",
        descriptionML: "സദ്യയുടെ പ്രധാന ഭാഗമായ പോഷകസമൃദ്ധമായ കുത്തരി.",
        image: "https://placehold.co/600x450/EEE/31343C?text=Matta+Rice",
        tags: ["Staple", "Nutritious"],
        tagsML: ["പ്രധാനം", "പോഷകപ്രദം"]
    },
    {
        id: 2,
        name: "Sambar",
        nameML: "സാമ്പാർ",
        price: 60,
        category: "curry",
        description: "Aromatic lentil stew rich with garden vegetables.",
        descriptionML: "പച്ചക്കറികളും പരിപ്പും ചേര്ന്ന സുഗന്ധപൂരിതമായ കറി.",
        image: "https://placehold.co/600x450/EEE/31343C?text=Sambar",
        tags: ["Spiced", "Flavorful"],
        tagsML: ["സുഗന്ധം", "രുചികരം"]
    },
    {
        id: 3,
        name: "Avial",
        nameML: "അവിയൽ",
        price: 90,
        category: "curry",
        description: "A divine blend of vegetables, coconut, and curd.",
        descriptionML: "പച്ചക്കറികളും തേങ്ങയും തൈരും ചേർന്ന ദിവ്യമായ കൂട്ട്.",
        image: "https://placehold.co/600x450/EEE/31343C?text=Avial",
        tags: ["Traditional", "Mild"],
        tagsML: ["പരമ്പരാഗതം", "മിതമായത്"]
    },
    {
        id: 4,
        name: "Parippu Curry",
        nameML: "പരിപ്പ് കറി",
        price: 50,
        category: "curry",
        description: "Golden moong dal seasoned with pure ghee.",
        descriptionML: "നെയ്യ് ചേർത്ത സ്വാദിഷ്ടമായ ചെറുപയർ പരിപ്പ് കറി.",
        image: "https://placehold.co/600x450/EEE/31343C?text=Parippu",
        tags: ["Comfort", "Classic"],
        tagsML: ["ലളിതം", "ക്ലാസിക്"]
    },
    {
        id: 5,
        name: "Cabbage Thoran",
        nameML: "ക്യാബേജ് തോരൻ",
        price: 70,
        category: "side",
        description: "Stir-fried farm fresh cabbage with grated coconut.",
        descriptionML: "തേങ്ങ ചേർത്ത ഫ്രഷ് ക്യാബേജ് തോരൻ.",
        image: "https://placehold.co/600x450/EEE/31343C?text=Thoran",
        tags: ["Fresh", "Side"],
        tagsML: ["ഫ്രഷ്", "തോരൻ"]
    },
    {
        id: 6,
        name: "Kaalan",
        nameML: "കാളൻ",
        price: 85,
        category: "curry",
        description: "Thick yogurt-based curry with sun-dried yam.",
        descriptionML: "തൈരും ചേനയും ചേർത്ത കുറുകിയ കറി.",
        image: "https://placehold.co/600x450/EEE/31343C?text=Kaalan",
        tags: ["Tangy", "Preserved"],
        tagsML: ["പുളിപ്പുള്ളത്", "പരമ്പരാഗതം"]
    },
    {
        id: 7,
        name: "Pappadam",
        nameML: "പപ്പടം",
        price: 20,
        category: "side",
        description: "Crispy lentil wafers, a festive crunch.",
        descriptionML: "സദ്യക്ക് ഒഴിവാക്കാനാവാത്ത മൊരിഞ്ഞ പപ്പടം.",
        image: "https://placehold.co/600x450/EEE/31343C?text=Pappadam",
        tags: ["Crispy", "Essential"],
        tagsML: ["മൊരിഞ്ഞത്", "നിർബന്ധം"]
    },
    {
        id: 8,
        name: "Ada Pradhaman",
        nameML: "അട പ്രഥമൻ",
        price: 120,
        category: "dessert",
        description: "Royal sweet delicacy with rice flakes and jaggery.",
        descriptionML: "അടയും ശർക്കരയും ചേർത്ത രാജകീയ പായസം.",
        image: "https://placehold.co/600x450/EEE/31343C?text=Pradhaman",
        tags: ["Sweet", "Signature"],
        tagsML: ["മധുരം", "സ്പെഷ്യൽ"]
    },
    {
        id: 9,
        name: "Palada Payasam",
        nameML: "പാലട പായസം",
        price: 130,
        category: "dessert",
        description: "Divine rice pudding slow-cooked in milk.",
        descriptionML: "പാലിൽ കുറുക്കിയെടുത്ത രുചികരമായ പായസം.",
        image: "https://placehold.co/600x450/EEE/31343C?text=Payasam",
        tags: ["Creamy", "Divine"],
        tagsML: ["പാൽരുചി", "ദിവ്യം"]
    }
];
